-- MySQL Script generated by MySQL Workbench
-- Fri Sep  8 01:29:32 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza` DEFAULT CHARACTER SET utf8mb4 ;
USE `pizza` ;

-- -----------------------------------------------------
-- Table `pizza`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`tienda` (
  `idtienda` INT(11) NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(125) NOT NULL,
  `cp` VARCHAR(20) NOT NULL,
  `localidad` VARCHAR(75) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtienda`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`personas` (
  `idpersonas` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido1` VARCHAR(45) NOT NULL,
  `apellido2` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `cp` VARCHAR(25) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `tipo` ENUM('cliente', 'empleado') NOT NULL,
  PRIMARY KEY (`idpersonas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pizza`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idcliente` INT(11) NULL,
  `fecha_registro` DATE NOT NULL,
  INDEX `fk_persona_idx` (`idcliente` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_persona`
    FOREIGN KEY (`idcliente`)
    REFERENCES `pizza`.`personas` (`idpersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`empleado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `idempleado` INT(11) NULL,
  `tipo` ENUM('cocinero', 'repartidor') NOT NULL,
  `salario` INT(5) NOT NULL,
  `idtienda` INT(11) NOT NULL,
  `fecha_contratacio` DATE NOT NULL,
  INDEX `fk_empleado_tienda1_idx` (`idtienda` ASC) VISIBLE,
  INDEX `fk_empleado_persona_idx` (`idempleado` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_empleado_tienda1`
    FOREIGN KEY (`idtienda`)
    REFERENCES `pizza`.`tienda` (`idtienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_persona`
    FOREIGN KEY (`idempleado`)
    REFERENCES `pizza`.`personas` (`idpersonas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`pedidos` (
  `idpedidos` INT(11) NOT NULL AUTO_INCREMENT,
  `pedido` ENUM('domicilio', 'tienda') NOT NULL,
  `date` DATE NOT NULL,
  `iditenda` INT(11) NOT NULL,
  `idclient` INT(11) NOT NULL,
  `empleado_id` INT(11) NOT NULL,
  PRIMARY KEY (`idpedidos`),
  INDEX `fk_id_tienda_idx` (`iditenda` ASC) VISIBLE,
  INDEX `fk_pedidos_cliente1_idx` (`idclient` ASC) VISIBLE,
  INDEX `fk_pedidos_empleado1_idx` (`empleado_id` ASC) VISIBLE,
  CONSTRAINT `fk_id_tienda`
    FOREIGN KEY (`iditenda`)
    REFERENCES `pizza`.`tienda` (`idtienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_cliente1`
    FOREIGN KEY (`idclient`)
    REFERENCES `pizza`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_empleado1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `pizza`.`empleado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`categoria` (
  `idcategoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`producto` (
  `idproducto` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('pizza', 'hamburguesa', 'bebida') NOT NULL,
  `img` VARCHAR(45) NULL DEFAULT NULL,
  `precio_total` DECIMAL(10,2) NOT NULL,
  `idcategoria` INT(11) NULL,
  PRIMARY KEY (`idproducto`),
  INDEX `fk_producto_categoria1_idx` (`idcategoria` ASC) VISIBLE,
  CONSTRAINT `fk_producto_categoria1`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `pizza`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza`.`detalle_pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`detalle_pedidos` (
  `idcantidad_pedidos` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `idpedidos` INT(11) NOT NULL,
  `idproducto` INT(11) NOT NULL,
  PRIMARY KEY (`idcantidad_pedidos`),
  INDEX `fk_id_pedidos_idx` (`idpedidos` ASC) VISIBLE,
  INDEX `fk_cantidad_pedidos_producto1_idx` (`idproducto` ASC) VISIBLE,
  CONSTRAINT `fk_id_pedidos`
    FOREIGN KEY (`idpedidos`)
    REFERENCES `pizza`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cantidad_pedidos_producto1`
    FOREIGN KEY (`idproducto`)
    REFERENCES `pizza`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
