select producto.nombre from producto;
select producto.nombre, precio from producto;
show columns from producto;
select producto.nombre, producto.precio, producto.precio * 1.10 from producto;
select producto.nombre, round (precio * 1.10, 2) as Dolares_estadounidenses, precio as Euro from producto;
select upper(producto.nombre), precio from producto;
select lower(producto.nombre), precio from producto;
select nombre, upper(substr(nombre, 1, 2)) as mayus from fabricante;
select producto.nombre as producto, round(precio) as round_price from producto;
select producto.nombre, truncate(precio, 0) as precio_truncado from producto;
select codigo_fabricante from producto;
select distinct(codigo_fabricante) from producto;
select producto.nombre from producto order by producto.nombre asc ;
select producto.nombre from producto order by producto.nombre desc;
select producto.nombre, precio from producto order by producto.nombre, precio desc;
select * from fabricante  limit 5;
select * from fabricante limit 3, 2	;
select producto.nombre, producto.precio as precio_min from producto order by producto.precio asc limit 1;
select producto.nombre, precio as precio_max from producto group by producto.nombre order by precio desc limit 1;
select producto.nombre from producto where producto.codigo_fabricante = 2;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante order by  fabricante.nombre;
select producto.codigo, producto.nombre, fabricante.codigo as codigo_fabricante, fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante;
select producto.nombre, producto.precio, fabricante.nombre from producto, fabricante where producto.codigo_fabricante = fabricante.codigo and producto.precio order by producto.precio asc limit 1;
select producto.nombre, producto.precio, fabricante.nombre from producto, fabricante where producto.codigo_fabricante = fabricante.codigo and producto.precio order by producto.precio desc limit 1;
select *  from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante where fabricante.nombre = 'Lenovo';
select * from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante where fabricante.nombre = 'Crucial' having producto.precio > 200;
select * from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante where fabricante.nombre = 'Asus' or fabricante.nombre = 'Hewlett-Packard' or fabricante.nombre = 'Seagate';
select * from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante where fabricante.nombre in ( 'Asus', 'Hewlett-Packard','Seagate');
select producto.nombre as producto, producto.precio from producto inner join fabricante on fabricante.codigo = producto.codigo where fabricante.nombre like '%e';
select producto.nombre as producto, producto.precio from producto inner join fabricante on fabricante.codigo = producto.codigo where fabricante.nombre like '%w%';
select producto.nombre as producto, producto.precio, fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo where producto.precio >= 180 order by producto.precio desc, producto.nombre;
select  fabricante.codigo,fabricante.nombre from fabricante inner join producto on  fabricante.codigo = producto.codigo_fabricante group by fabricante.codigo, nombre;
select * from fabricante left join producto on fabricante.codigo = producto.codigo_fabricante;
select *  from fabricante left join producto on fabricante.codigo = producto.codigo_fabricante where producto.codigo_fabricante is null;
select * from producto where producto.codigo_fabricante = (select fabricante.codigo from fabricante where fabricante.nombre = 'Lenovo');
SELECT * from producto where precio = (select MAX(precio) from producto where codigo_fabricante = (select codigo from fabricante where fabricante.nombre = 'Lenovo'));
select producto.nombre from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Lenovo') order by precio desc limit 1;
select producto.nombre from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Hewlett-Packard') order by precio  limit 1;
select * from producto where precio >= ( select MAX(precio) from producto where codigo_fabricante = ( select codigo from fabricante where nombre = 'Lenovo'));
SELECT * from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Asus') and precio > (select avg(precio) from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Asus'));