select nombre_producto from producto;
select nombre_producto, precio from producto;
select * from producto;
select producto.nombre_producto, producto.precio, producto.precio * 1.10 from producto;
select producto.nombre_producto, round (precio * 1.10, 2) as Dolares_estadounidenses, precio as Euro from producto;
select upper(nombre_producto), precio from producto;
select lower(nombre_producto), precio from producto;
select nombre, upper(substr(nombre, 1, 2)) as mayus from fabricante;
select producto.nombre_producto as producto, round(precio) as round_price from producto;
select nombre_producto, truncate(precio, 0) as precio_truncado from producto;
select codigo_fabricante from producto;
select distinct(codigo_fabricante) from producto;
select nombre_producto from producto order by nombre_producto asc ;
select nombre_producto from producto order by nombre_producto desc;
select nombre_producto, precio from producto order by nombre_producto, precio desc;
select * from fabricante  limit 5;
select * from fabricante limit 3, 2	;
select nombre_producto, producto.precio as precio_min from producto order by producto.precio asc limit 1;
select nombre_producto, precio as precio_max from producto group by nombre_producto order by precio desc limit 1;
select producto.nombre_producto from producto where producto.codigo_fabricante = 2;
select producto.nombre_producto, producto.precio, fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante;
select producto.nombre_producto, producto.precio, fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante order by  fabricante.nombre;
select producto.codigo, producto.nombre_producto, fabricante.codigo as codigo_fabricante, fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante;
select producto.nombre_producto, min(producto.precio), fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante limit 1;
select producto.nombre_producto, max(producto.precio), fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante limit 1;
select *  from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante where fabricante.nombre = 'Lenovo';
select * from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante where fabricante.nombre = 'Crucial' having producto.precio > 200;
select * from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante where fabricante.nombre = 'Asus' or fabricante.nombre = 'Hewlett-Packard' or fabricante.nombre = 'Seagate';
select * from producto inner join fabricante on fabricante.codigo = producto.codigo_fabricante where fabricante.nombre in ( 'Asus', 'Hewlett-Packard','Seagate');
select producto.nombre_producto as producto, producto.precio from producto inner join fabricante on fabricante.codigo = producto.codigo where fabricante.nombre like '%e';
select producto.nombre_producto as producto, producto.precio from producto inner join fabricante on fabricante.codigo = producto.codigo where fabricante.nombre like '%w%';
select producto.nombre_producto as producto, producto.precio, fabricante.nombre as fabricante from producto inner join fabricante on fabricante.codigo = producto.codigo where producto.precio >= 180 order by producto.precio desc, producto.nombre_producto;
select  fabricante.codigo,fabricante.nombre from fabricante inner join producto on  fabricante.codigo = producto.codigo_fabricante group by fabricante.codigo, nombre;
select * from fabricante left join producto on fabricante.codigo = producto.codigo_fabricante;
select *  from fabricante left join producto on fabricante.codigo = producto.codigo_fabricante where producto.codigo_fabricante is null;
select * from producto where producto.codigo_fabricante = (select fabricante.codigo from fabricante where fabricante.nombre = 'Lenovo');
SELECT * FROM producto WHERE precio = (SELECT MAX(precio) FROM producto WHERE codigo_fabricante = (SELECT codigo FROM fabricante WHERE fabricante.nombre = 'Lenovo'));
select nombre_producto from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Lenovo') order by precio desc limit 1;
select nombre_producto from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Hewlett-Packard') order by precio  limit 1;
SELECT * FROM producto WHERE precio >= ( SELECT MAX(precio) FROM producto WHERE codigo_fabricante = ( SELECT codigo FROM fabricante WHERE nombre = 'Lenovo'));
SELECT * from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Asus') and precio > (select avg(precio) from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'Asus'));